### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by mturk90049** [mkrobert/efficiency-for-iws#1]
this was a great, convenient script, but it is no longer working for me as of the last couple of weeks. did something change? thanks!

**Comment by mturk90049** [comment]
update: i was able to fix it myself by changing the @include line from
https://**www**.masseurfinder.com/s/tools/aws_turk/*
to
https://**my**.masseurfinder.com/s/tools/aws_turk/*

**Comment by mkrobert** [comment]
good to know. thanks
